using System;
using System.Collections.Generic;
using System.Text;

namespace CoreEngine.Spike.UI
{
    /// <summary>
    /// String table for the Phase 0.6 localisation check (docs/10 §5): English, Uzbek (Latin script,
    /// with oʻ/gʻ written with U+02BB and the tutuq belgisi ʼ with U+02BC) and Russian.
    /// The Uzbek and Russian texts are AI drafts: the owner reviews them (docs/13 R22, R23).
    /// Compiler output and code are never translated.
    /// </summary>
    public static class SpikeStrings
    {
        public static readonly string[] LanguageCodes = { "en", "uz", "ru" };
        public static readonly string[] LanguageButtons = { "EN", "OʻZ", "RU" };

        static readonly Dictionary<string, string[]> Table = new Dictionary<string, string[]>
        {
            ["lang.name"] = new[] { "English", "Oʻzbekcha", "Русский" },
            ["mode.build"] = new[] { "Build", "Yigʻish", "Сборка" },
            ["mode.wire"] = new[] { "Wire", "Simlash", "Провода" },
            ["mode.code"] = new[] { "Code", "Kod", "Код" },
            ["mode.test"] = new[] { "Test", "Sinov", "Тест" },
            ["panel.code"] = new[] { "Code", "Kod", "Код" },
            ["panel.inspector"] = new[] { "Inspector", "Xususiyatlar", "Свойства" },
            ["panel.console"] = new[] { "Console", "Konsol", "Консоль" },
            ["panel.serial"] = new[] { "Serial Monitor", "Port monitori", "Монитор порта" },
            ["panel.events"] = new[] { "Event log", "Hodisalar jurnali", "Журнал событий" },
            ["dock.empty"] = new[] { "Drag a panel tab here", "Panel yorligʻini shu yerga torting", "Перетащите сюда вкладку панели" },
            ["code.status"] = new[] { "Ln {0}, Col {1} · {2} lines", "{0}-qator, {1}-ustun · {2} qator", "Стр. {0}, стлб. {1} · строк: {2}" },
            ["insp.sensor"] = new[] { "HC-SR04 ultrasonic sensor", "HC-SR04 ultratovush sensori", "Ультразвуковой датчик HC-SR04" },
            ["insp.distance"] = new[] { "Distance", "Masofa", "Расстояние" },
            ["insp.measurements"] = new[] { "Measurements", "Oʻlchovlar soni", "Число измерений" },
            ["insp.noEcho"] = new[] { "no echo", "aks-sado yoʻq", "нет эха" },
            ["insp.driver"] = new[] { "L298N motor driver", "L298N motor drayveri", "Драйвер моторов L298N" },
            ["insp.supply"] = new[] { "Supply voltage", "Taʼminot kuchlanishi", "Напряжение питания" },
            ["insp.leftMotor"] = new[] { "Left motor", "Chap motor", "Левый мотор" },
            ["insp.rightMotor"] = new[] { "Right motor", "Oʻng motor", "Правый мотор" },
            ["insp.wheelSpeed"] = new[] { "Wheel speed", "Gʻildirak tezligi", "Скорость колёс" },
            ["insp.board"] = new[] { "Arduino Uno (emulated)", "Arduino Uno (emulyatsiya)", "Arduino Uno (эмуляция)" },
            ["insp.emulatedTime"] = new[] { "Emulated time", "Emulyatsiya vaqti", "Время эмуляции" },
            ["insp.emulatorLoad"] = new[] { "Emulator load", "Emulyator yuklamasi", "Нагрузка эмулятора" },
            ["insp.perStep"] = new[] { "{0:F2} ms per 10 ms step", "10 ms qadamga {0:F2} ms", "{0:F2} мс на шаг 10 мс" },
            ["unit.cm"] = new[] { "cm", "sm", "см" },
            ["unit.mm"] = new[] { "mm", "mm", "мм" },
            ["unit.g"] = new[] { "g", "g", "г" },
            ["unit.V"] = new[] { "V", "V", "В" },
            ["unit.A"] = new[] { "A", "A", "А" },
            ["unit.s"] = new[] { "s", "s", "с" },
            ["unit.rads"] = new[] { "rad/s", "rad/s", "рад/с" },
            ["serial.autoscroll"] = new[] { "Autoscroll", "Avtoaylantirish", "Автопрокрутка" },
            ["serial.baud"] = new[] { "{0} baud", "{0} bod", "{0} бод" },
            ["console.example"] = new[] { "Example of an error card:", "Xato kartasi namunasi:", "Пример карточки ошибки:" },
            ["console.helpTitle"] = new[] { "What this error means", "Bu xato nimani anglatadi", "Что означает эта ошибка" },
            ["console.helpText"] = new[]
            {
                "A statement is missing its semicolon (;). Add ; at the end of the line before the marked one.",
                "Buyruq oxirida nuqtali vergul (;) yetishmayapti. Belgilangan qatordan oldingi qator oxiriga ; qoʻying.",
                "В конце команды не хватает точки с запятой (;). Поставьте ; в конце строки перед отмеченной.",
            },
            ["event.stall"] = new[] { "{0} motor stalled: {1:F2} A", "{0} motor toʻxtab qoldi: {1:F2} A", "{0} мотор остановлен нагрузкой: {1:F2} А" },
            ["event.tips"] = new[] { "Tipped onto its {0}: {1} drags on the floor", "{0} ogʻib ketdi: {1} polga sudralmoqda", "Завалился {0}: {1} волочится по полу" },
            ["tip.front"] = new[] { "front", "Oldinga", "вперёд" },
            ["tip.back"] = new[] { "back", "Orqaga", "назад" },
            ["tip.left"] = new[] { "left side", "Chapga", "влево" },
            ["tip.right"] = new[] { "right side", "Oʻngga", "вправо" },
            ["tip.body"] = new[] { "the body", "korpus", "корпус" },
            ["stance.drags"] = new[]
            {
                "⚠ Tips onto its {0}: {1} drags on the floor, so it turns slowly. Put a ball caster there.",
                "⚠ {0} ogʻib ketadi: {1} polga sudraladi, shuning uchun sekin buriladi. U yerga sharikli tayanch qoʻying.",
                "⚠ Заваливается {0}: {1} волочится по полу, поэтому робот медленно поворачивает. Поставьте туда шаровую опору.",
            },
            ["loose.pieces"] = new[]
            {
                "⚠ Not attached to the robot: {0}. Loose pieces fall off: set them on the plate or the body.",
                "⚠ Robotga biriktirilmagan: {0}. Boʻsh qismlar tushib ketadi: ularni plastina yoki korpus ustiga qoʻying.",
                "⚠ Не прикреплено к роботу: {0}. Незакреплённое отвалится: поставьте это на пластину или корпус.",
            },
            ["loose.more"] = new[] { "and {0} more", "va yana {0} ta", "и ещё {0}" },
            ["loose.none"] = new[] { "Every part is attached to the robot", "Barcha qismlar robotga biriktirilgan", "Все детали прикреплены к роботу" },
            ["sonar.up"] = new[]
            {
                "⚠ The HC-SR04 looks {0:F0}° up: it sees over low boxes. Turn it level (Rotation X 0).",
                "⚠ HC-SR04 {0:F0}° yuqoriga qaragan: past qutilarni koʻrmaydi. Uni tekis qiling (Burilish X 0).",
                "⚠ HC-SR04 смотрит на {0:F0}° вверх: низкие коробки он не видит. Поставьте его ровно (Поворот X 0).",
            },
            ["sonar.down"] = new[]
            {
                "⚠ The HC-SR04 looks {0:F0}° down: it sees the floor. Turn it level (Rotation X 0).",
                "⚠ HC-SR04 {0:F0}° pastga qaragan: polni koʻradi. Uni tekis qiling (Burilish X 0).",
                "⚠ HC-SR04 смотрит на {0:F0}° вниз: он видит пол. Поставьте его ровно (Поворот X 0).",
            },
            ["studio.balance"] = new[] { "Balance", "Muvozanat", "Баланс" },
            ["studio.balance.tip"] = new[]
            {
                "Centre of mass (yellow) and what the robot stands on: green holds, red tips",
                "Ogʻirlik markazi (sariq) va robot turgan joy: yashil ushlaydi, qizil agʻdaradi",
                "Центр масс (жёлтый) и на чём стоит робот: зелёное держит, красное — опрокинется",
            },
            ["balance.noWheels"] = new[] { "No wheels yet: the centre of mass is the yellow ball", "Hali gʻildirak yoʻq: ogʻirlik markazi sariq shar", "Колёс пока нет: центр масс — жёлтый шар" },
            ["stance.rolls"] = new[] { "Stands on its wheels and ball caster", "Gʻildiraklari va sharikli tayanchida turadi", "Стоит на колёсах и шаровой опоре" },
            ["event.left"] = new[] { "Left", "Chap", "Левый" },
            ["event.right"] = new[] { "Right", "Oʻng", "Правый" },
            ["arena.restart"] = new[] { "↺ Restart (R)", "↺ Qaytadan (R)", "↺ Заново (R)" },
            ["arena.follow"] = new[] { "Follow", "Orqadan", "Сзади" },
            ["arena.orbit"] = new[] { "Free", "Erkin", "Свободно" },
            ["arena.top"] = new[] { "Top", "Yuqoridan", "Сверху" },
            ["arena.side"] = new[] { "Side", "Yondan", "Сбоку" },
            ["arena.eye"] = new[] { "Robot's eye", "Robot koʻzi", "Глазами робота" },
            ["arena.whole"] = new[] { "Arena", "Maydon", "Арена" },
            ["arena.key"] = new[] { "Key {0}", "{0} tugmasi", "Клавиша {0}" },
            ["ui.hint"] = new[]
            {
                "F1: hide panels · 1–6 or C: camera · drag the view to turn it, the wheel zooms · drag a tab to move its panel",
                "F1: panellarni yashirish · 1–6 yoki C: kamera · koʻrinishni burish uchun torting, gʻildirak bilan yaqinlashtiring · panelni koʻchirish uchun yorligʻini torting",
                "F1: скрыть панели · 1–6 или C: камера · тяните вид, чтобы повернуть, колёсико приближает · перетащите вкладку, чтобы переместить панель",
            },
            // ---- Garage (ADR-0009) ----
            ["nav.garage"] = new[] { "Garage", "Garaj", "Гараж" },
            ["nav.notebook"] = new[] { "Notebook", "Daftar", "Блокнот" },
            ["nav.shop"] = new[] { "Shop", "Doʻkon", "Магазин" },
            ["nav.workshop"] = new[] { "Workshop", "Ustaxona", "Мастерская" },
            ["nav.back"] = new[] { "◀ Garage", "◀ Garaj", "◀ Гараж" },
            ["start"] = new[] { "START", "BOSHLASH", "СТАРТ" },
            ["arena"] = new[] { "Arena", "Arena", "Арена" },
            ["arena.obstacles"] = new[] { "Obstacle field", "Toʻsiqlar maydoni", "Поле препятствий" },
            ["arena.line"] = new[] { "Line track (Phase 2)", "Chiziq yoʻli (2-bosqich)", "Трасса по линии (фаза 2)" },
            ["arena.maze"] = new[] { "Maze (Phase 2)", "Labirint (2-bosqich)", "Лабиринт (фаза 2)" },
            ["arena.sumo"] = new[] { "Sumo ring (Phase 2)", "Sumo ringi (2-bosqich)", "Ринг для сумо (фаза 2)" },
            ["arena.later"] = new[] { "This arena comes in Phase 2. The obstacle field is ready.", "Bu arena 2-bosqichda qoʻshiladi. Toʻsiqlar maydoni tayyor.", "Эта арена появится в фазе 2. Поле препятствий уже готово." },
            ["garage.hint"] = new[]
            {
                "Drag: turn · Middle button: move · Wheel: zoom · Double-click: look closer",
                "Tortish: aylantirish · Oʻrta tugma: surish · Gʻildirak: yaqinlashtirish · Ikki marta bosish: yaqindan koʻrish",
                "Тянуть: вращать · Средняя кнопка: сдвинуть · Колесо: приблизить · Двойной щелчок: смотреть ближе",
            },
            ["act.build"] = new[] { "Build", "Yigʻish", "Сборка" },
            ["act.test"] = new[] { "Test", "Sinash", "Тест" },
            ["act.test.tip"] = new[] { "Drive it in the arena now (F5)", "Hozir maydonda yurgizing (F5)", "Запустить на арене сейчас (F5)" },
            ["act.build.sub"] = new[] { "Put parts on your robot", "Robotga qismlar qoʻying", "Поставить детали на робота" },
            ["act.wire.sub"] = new[] { "Join the parts with wires", "Qismlarni simlar bilan ulang", "Соединить детали проводами" },
            ["act.code.sub"] = new[] { "Write its program", "Uning dasturini yozing", "Написать его программу" },
            ["act.body.sub"] = new[] { "Make its body", "Uning korpusini yasang", "Сделать его корпус" },
            ["act.customize.sub"] = new[] { "Change its colours", "Ranglarini oʻzgartiring", "Поменять его цвета" },
            ["act.repair.sub"] = new[] { "Find and fix problems", "Muammolarni toping va tuzating", "Найти и исправить неполадки" },
            ["card.robot"] = new[] { "ROBOT", "ROBOT", "РОБОТ" },
            ["card.fix"] = new[] { "Fix", "Tuzatish", "Исправить" },
            ["card.statusReady"] = new[] { "READY", "TAYYOR", "ГОТОВ" },
            ["card.statusCheck"] = new[] { "{0} TO CHECK", "{0} TA TEKSHIRISH", "ПРОВЕРИТЬ: {0}" },
            ["act.wire"] = new[] { "Wire", "Simlash", "Провода" },
            ["act.code"] = new[] { "Code", "Kod", "Код" },
            ["act.body"] = new[] { "Body", "Korpus", "Корпус" },
            ["act.customize"] = new[] { "Customize", "Bezash", "Оформление" },
            ["act.repair"] = new[] { "Check & repair", "Tekshirish va taʼmirlash", "Проверка и ремонт" },
            ["card.board"] = new[] { "Board", "Plata", "Плата" },
            ["card.noBoard"] = new[] { "none", "yoʻq", "нет" },
            ["card.sketch"] = new[] { "Sketch", "Sketch", "Скетч" },
            ["card.compiled"] = new[] { "compiled, {0} bytes", "kompilyatsiya qilingan, {0} bayt", "скомпилирован, {0} байт" },
            ["card.noSketch"] = new[] { "no sketch yet", "hali sketch yoʻq", "скетча пока нет" },
            ["card.parts"] = new[] { "Parts", "Qismlar", "Детали" },
            ["card.mass"] = new[] { "Mass", "Massa", "Масса" },
            ["card.battery"] = new[] { "Battery", "Batareya", "Батарея" },
            ["card.ready"] = new[] { "✓ Ready to start", "✓ Boshlashga tayyor", "✓ Готов к старту" },
            ["warn.noBoard"] = new[] { "⚠ No board yet: add one in Build", "⚠ Plata yoʻq: Yigʻish boʻlimida qoʻshing", "⚠ Платы нет: добавьте её в сборке" },
            ["warn.batteryLow"] = new[] { "⚠ Battery low: {0:F0} %", "⚠ Batareya kam: {0:F0} %", "⚠ Батарея почти разряжена: {0:F0} %" },
            ["warn.batteryEmpty"] = new[] { "⚠ Battery empty", "⚠ Batareya tugagan", "⚠ Батарея разряжена" },
            ["warn.motorBurnt"] = new[] { "⚠ {0} motor burnt out", "⚠ {0} motor kuyib qolgan", "⚠ {0} мотор сгорел" },
            ["warn.notUploaded"] = new[] { "⚠ Code changed, not uploaded yet", "⚠ Kod oʻzgargan, hali yuklanmagan", "⚠ Код изменён, но не загружен" },
            ["warn.trying"] = new[] { "★ Trying a pack finish", "★ Toʻplam bezagi sinab koʻrilmoqda", "★ Примерка оформления из набора" },
            ["side.left"] = new[] { "Left", "Chap", "Левый" },
            ["side.right"] = new[] { "Right", "Oʻng", "Правый" },
            ["bar.new"] = new[] { "+ New robot", "+ Yangi robot", "+ Новый робот" },
            ["bar.empty"] = new[] { "empty chassis", "boʻsh shassi", "пустое шасси" },
            ["bar.parts"] = new[] { "{0} parts, no board", "{0} ta qism, platasiz", "деталей: {0}, без платы" },
            ["cust.body"] = new[] { "Body finish", "Korpus bezagi", "Отделка корпуса" },
            ["cust.wheels"] = new[] { "Wheels", "Gʻildiraklar", "Колёса" },
            ["cust.free"] = new[] { "Free", "Bepul", "Бесплатно" },
            ["cust.trying"] = new[] { "Trying {0} from the {1}. You can test it everywhere; only owned finishes are saved.", "{1} dan {0} sinab koʻrilmoqda. Uni hamma joyda sinash mumkin; faqat sotib olingan bezaklar saqlanadi.", "Примерка: {0} из набора «{1}». Её можно проверить везде; сохраняется только купленное оформление." },
            ["cust.stop"] = new[] { "Stop trying", "Sinashni toʻxtatish", "Отменить примерку" },
            ["pack.carbonMetal"] = new[] { "Carbon & Metal pack", "Karbon va metall toʻplami", "Карбон и металл" },
            ["pack.neon"] = new[] { "Neon pack", "Neon toʻplami", "Неон" },
            ["rep.readiness"] = new[] { "Readiness", "Tayyorlik", "Готовность" },
            ["rep.parts"] = new[] { "Parts", "Qismlar", "Детали" },
            ["rep.power"] = new[] { "Power: 4×AA, {0:F2} V", "Quvvat: 4×AA, {0:F2} V", "Питание: 4×AA, {0:F2} В" },
            ["rep.sketch"] = new[] { "Sketch compiled for Arduino Uno, {0} bytes", "Sketch Arduino Uno uchun kompilyatsiya qilingan, {0} bayt", "Скетч скомпилирован для Arduino Uno, {0} байт" },
            ["rep.ok"] = new[] { "OK", "Soz", "Исправен" },
            ["rep.burnt"] = new[] { "Burnt out", "Kuygan", "Сгорел" },
            ["rep.motor"] = new[] { "{0} TT motor: {1:F0} °C now, peak {2:F0} °C", "{0} TT motor: hozir {1:F0} °C, eng yuqori {2:F0} °C", "{0} мотор TT: сейчас {1:F0} °C, максимум {2:F0} °C" },
            ["rep.battery"] = new[] { "Batteries 4×AA: {0:F1} % charge", "Batareyalar 4×AA: {0:F1} % zaryad", "Батарейки 4×AA: заряд {0:F1} %" },
            ["rep.replace"] = new[] { "Replace (free)", "Almashtirish (bepul)", "Заменить (бесплатно)" },
            ["rep.replaceBatteries"] = new[] { "Replace batteries (free)", "Batareyalarni almashtirish (bepul)", "Заменить батарейки (бесплатно)" },
            ["rep.why"] = new[] { "Why it broke", "Nega buzildi", "Почему сломалось" },
            ["rep.whyF18"] = new[] { "The motor was stalled. At 1.05 A its 4 Ω winding turns 4.4 W into heat, and above 120 °C the insulation melts and the winding breaks. Real robots avoid this by noticing when they are stuck and stopping the motors.", "Motor tiqilib qolgan edi. 1,05 A da uning 4 Ω chulgʻami 4,4 W issiqlik chiqaradi, 120 °C dan yuqorida izolyatsiya erib, chulgʻam uziladi. Haqiqiy robotlar tiqilib qolganini sezib, motorlarni toʻxtatadi.", "Мотор был заблокирован. При 1,05 А его обмотка 4 Ом выделяет 4,4 Вт тепла, а выше 120 °C изоляция плавится и обмотка обрывается. Настоящие роботы замечают, что застряли, и останавливают моторы." },
            ["rep.noParts"] = new[] { "Only the chassis plate so far.", "Hozircha faqat shassi paneli.", "Пока только пластина шасси." },
            ["code.upload"] = new[] { "Upload", "Yuklash", "Загрузить" },
            ["code.close"] = new[] { "Close", "Yopish", "Закрыть" },
            ["code.compiling"] = new[] { "Compiling with arduino-cli…", "arduino-cli bilan kompilyatsiya…", "Компиляция в arduino-cli…" },
            ["code.ok"] = new[] { "Uploaded: {0} bytes, compiled in {1:F1} s. START runs the new code.", "Yuklandi: {0} bayt, {1:F1} s da kompilyatsiya qilindi. BOSHLASH yangi kodni ishga tushiradi.", "Загружено: {0} байт, компиляция {1:F1} с. СТАРТ запустит новый код." },
            ["code.failed"] = new[] { "Not uploaded: {0} errors. Click an error to jump to its line.", "Yuklanmadi: {0} ta xato. Qatoriga oʻtish uchun xatoni bosing.", "Не загружено: ошибок {0}. Нажмите на ошибку, чтобы перейти к строке." },
            ["code.noToolchain"] = new[] { "Arduino toolchain not found: run tools/fetch-toolchain.ps1 once.", "Arduino vositalari topilmadi: tools/fetch-toolchain.ps1 ni bir marta ishga tushiring.", "Инструменты Arduino не найдены: один раз запустите tools/fetch-toolchain.ps1." },
            ["page.notebookInfo"] = new[] { "Datasheet cards for every part, error help and \"why it broke\" cards, in English, Uzbek and Russian. Comes in Phase 1.", "Har bir qism uchun maʼlumot kartalari, xato yordami va \"nega buzildi\" kartalari: ingliz, oʻzbek va rus tillarida. 1-bosqichda keladi.", "Карточки с даташитами всех деталей, помощь по ошибкам и карточки «почему сломалось» на английском, узбекском и русском. Появится в фазе 1." },
            ["page.workshopInfo"] = new[] { "Share your robots, bodies and arenas on the Steam Workshop and try other players' robots. Comes in Phase 3.", "Robotlaringiz, korpuslaringiz va arenalaringizni Steam Workshop da ulashing va boshqa oʻyinchilarning robotlarini sinab koʻring. 3-bosqichda keladi.", "Делитесь роботами, корпусами и аренами в Мастерской Steam и пробуйте роботов других игроков. Появится в фазе 3." },
            ["page.shopInfo"] = new[] { "Paid packs planned for release (ADR-0007). Not on sale yet:", "Chiqishga rejalashtirilgan pullik toʻplamlar (ADR-0007). Hali sotuvda emas:", "Платные наборы, запланированные к выходу (ADR-0007). Пока не продаются:" },
            ["shop.mega"] = new[] { "Mega 2560 Pack: a real Arduino Mega board with its own emulated ATmega2560", "Mega 2560 toʻplami: oʻz emulyatsiya qilingan ATmega2560 si bilan haqiqiy Arduino Mega platasi", "Набор Mega 2560: настоящая плата Arduino Mega с эмуляцией ATmega2560" },
            ["shop.carbon"] = new[] { "Carbon & Metal pack: carbon fibre, aluminium and anodized finishes, chrome hubs", "Karbon va metall toʻplami: karbon tola, alyuminiy va anodlangan bezaklar, xrom gupchaklar", "Набор «Карбон и металл»: карбон, алюминий, анодированные отделки, хромированные диски" },
            ["shop.neon"] = new[] { "Neon pack: neon finishes and hubs", "Neon toʻplami: neon bezaklar va gupchaklar", "Набор «Неон»: неоновые отделки и диски" },
            ["shop.bundle"] = new[] { "Supporter bundle: all three packs, about 30 % off", "Qoʻllab-quvvatlovchi toʻplami: uchala toʻplam, taxminan 30 % chegirma", "Набор поддержки: все три набора со скидкой около 30 %" },
            ["shop.try"] = new[] { "Every pack finish can be tried in Customize.", "Har bir toʻplam bezagini Bezash boʻlimida sinab koʻrish mumkin.", "Любую отделку из наборов можно примерить в оформлении." },
            ["page.close"] = new[] { "Close", "Yopish", "Закрыть" },
            ["settings.title"] = new[] { "Settings", "Sozlamalar", "Настройки" },
            ["settings.language"] = new[] { "Language", "Til", "Язык" },
            ["settings.size"] = new[] { "Interface size", "Interfeys oʻlchami", "Размер интерфейса" },
            ["settings.sizeNote"] = new[]
            {
                "The interface grows with the screen by itself; this makes it bigger or smaller than that.",
                "Interfeys ekran bilan birga oʻzi kattalashadi; bu uni undan kattaroq yoki kichikroq qiladi.",
                "Интерфейс сам растёт вместе с экраном; здесь его можно сделать крупнее или мельче.",
            },
            ["arena.change"] = new[] { "Change", "Oʻzgartirish", "Сменить" },
            ["arena.pick"] = new[] { "Choose an arena", "Maydonni tanlang", "Выберите арену" },
            ["arena.obstacles.goal"] = new[] { "Drive round the boxes without touching them", "Qutilarga tegmasdan aylanib oʻting", "Объезжайте коробки, не касаясь их" },
            ["arena.obstacles.size"] = new[] { "3 × 3 m floor · 9 boxes", "3 × 3 m pol · 9 ta quti", "Пол 3 × 3 м · 9 коробок" },
            ["arena.needsSonar"] = new[] { "Needs a distance sensor (HC-SR04)", "Masofa sensori kerak (HC-SR04)", "Нужен датчик расстояния (HC-SR04)" },
            ["arena.easy"] = new[] { "Easy", "Oson", "Легко" },
            ["arena.soon"] = new[] { "More arenas soon", "Tez orada yangi maydonlar", "Скоро новые арены" },
            ["arena.soon.list"] = new[] { "Line track · Maze · Sumo ring", "Chiziq yoʻli · Labirint · Sumo ringi", "Трасса по линии · Лабиринт · Ринг для сумо" },
            ["event.burnt"] = new[] { "{0} motor burnt out (F18): {1:F0} °C", "{0} motor kuyib qoldi (F18): {1:F0} °C", "{0} мотор сгорел (F18): {1:F0} °C" },
            // ---- Garage edit modes: Build, Wire, Body ----
            ["garage.hint.build"] = new[] { "Click a part to select it · drag it on the deck · R rotates · Del removes · right-drag turns the view · wheel zooms", "Qismni tanlash uchun bosing · uni panel ustida suring · R buradi · Del olib tashlaydi · oʻng tugma bilan tortish koʻrinishni aylantiradi · gʻildirak yaqinlashtiradi", "Щёлкните деталь, чтобы выбрать её · тяните её по панели · R поворачивает · Del удаляет · правая кнопка вращает вид · колесо — масштаб" },
            ["garage.hint.wire"] = new[] { "Drag from one pin to another, or click one pin and then the other · Look at a part to see its pin names · click a wire and press Del to remove it · Esc cancels", "Bir pindan boshqasiga torting yoki avval bir pinni, keyin ikkinchisini bosing · pin nomlarini koʻrish uchun qismga qarang · simni bosib, Del bilan olib tashlang · Esc bekor qiladi", "Протяните от одного вывода к другому или щёлкните один вывод, затем другой · «Показать» деталь — увидите названия выводов · щёлкните провод и нажмите Del, чтобы убрать его · Esc отменяет" },
            ["garage.hint.body"] = new[] { "Every change rebuilds the plates with Manifold · Export STL for a 3D printer or a laser cutter", "Har bir oʻzgarish panellarni Manifold bilan qayta quradi · 3D printer yoki lazer kesgich uchun STL eksport qiling", "Каждое изменение перестраивает пластины через Manifold · экспорт STL для 3D-принтера или лазерной резки" },
            ["edit.undo"] = new[] { "Undo (Ctrl+Z)", "Bekor qilish (Ctrl+Z)", "Отменить (Ctrl+Z)" },
            ["edit.nothingToUndo"] = new[] { "Nothing to undo.", "Bekor qilinadigan narsa yoʻq.", "Отменять нечего." },
            ["build.bin"] = new[] { "Parts bin", "Qismlar qutisi", "Ящик деталей" },
            ["build.add"] = new[] { "Add", "Qoʻshish", "Добавить" },
            ["build.count"] = new[] { "{0} of {1} fitted · {2} g", "{1} tadan {0} tasi oʻrnatilgan · {2} g", "установлено {0} из {1} · {2} г" },
            ["build.selected"] = new[] { "Selected part", "Tanlangan qism", "Выбранная деталь" },
            ["build.selectHint"] = new[] { "Click a part on the robot to select it. Parts on the top deck can be dragged and turned; motors, the sensor, the caster and the battery holder have fixed places.", "Tanlash uchun robotdagi qismni bosing. Yuqori paneldagi qismlarni surish va burish mumkin; motorlar, sensor, gʻildirakcha va batareya qutisining joyi oʻzgarmas.", "Щёлкните деталь на роботе, чтобы выбрать её. Детали на верхней панели можно двигать и поворачивать; у моторов, датчика, опорного колеса и батарейного отсека места постоянные." },
            ["build.onDeck"] = new[] { "On the top deck at x {0:F0} mm, z {1:F0} mm, turned {2}°", "Yuqori panelda: x {0:F0} mm, z {1:F0} mm, {2}° burilgan", "На верхней панели: x {0:F0} мм, z {1:F0} мм, поворот {2}°" },
            ["build.place.left"] = new[] { "Left motor mount, under the bottom plate", "Chap motor oʻrni, pastki panel ostida", "Левое крепление мотора, под нижней пластиной" },
            ["build.place.right"] = new[] { "Right motor mount, turned round (mirrored)", "Oʻng motor oʻrni, teskari burilgan (koʻzgu kabi)", "Правое крепление мотора, развёрнуто (зеркально)" },
            ["build.place.front"] = new[] { "Sensor bracket at the front", "Old tomondagi sensor tutqichi", "Кронштейн датчика спереди" },
            ["build.place.caster"] = new[] { "Under the front of the bottom plate", "Pastki panelning old qismi ostida", "Под передней частью нижней пластины" },
            ["build.place.between"] = new[] { "Between the two decks", "Ikki panel orasida", "Между двумя панелями" },
            ["build.place.back"] = new[] { "On the deck, at the back", "Panelda, orqa tomonda", "На панели, сзади" },
            ["build.rotate"] = new[] { "Rotate 90° (R)", "90° burish (R)", "Повернуть на 90° (R)" },
            ["build.remove"] = new[] { "Remove (Del)", "Olib tashlash (Del)", "Убрать (Del)" },
            ["build.full"] = new[] { "No more of this part fits this robot.", "Bu robotga bu qismdan boshqa sigʻmaydi.", "Больше таких деталей на этого робота не поместится." },
            ["build.noRoom"] = new[] { "No room there: it would overlap another part.", "U yerda joy yoʻq: boshqa qism bilan ustma-ust tushadi.", "Там нет места: деталь налезет на другую." },
            ["build.overlap"] = new[] { "⚠ {0} and {1} overlap on the deck", "⚠ {0} va {1} panelda ustma-ust tushgan", "⚠ {0} и {1} налезают друг на друга" },
            ["build.removed"] = new[] { "Removed, with its wires. Ctrl+Z brings it back.", "Simlari bilan birga olib tashlandi. Ctrl+Z qaytaradi.", "Убрано вместе с проводами. Ctrl+Z вернёт." },
            ["build.mass"] = new[] { "Robot mass: {0:F0} g", "Robot massasi: {0:F0} g", "Масса робота: {0:F0} г" },
            ["build.newBoard"] = new[] { "A new Uno runs Blink from the factory. Write your own sketch in Code.", "Yangi Uno zavoddan Blink dasturi bilan keladi. Oʻz sketchingizni Kod boʻlimida yozing.", "Новая Uno с завода выполняет Blink. Свой скетч напишите в разделе «Код»." },
            ["wire.colour"] = new[] { "Wire colour", "Sim rangi", "Цвет провода" },
            ["wire.auto"] = new[] { "Auto: red for power, black for ground", "Avto: quvvat uchun qizil, yer uchun qora", "Авто: красный для питания, чёрный для земли" },
            ["wire.check"] = new[] { "Wiring check", "Simlarni tekshirish", "Проверка проводки" },
            ["wire.ok"] = new[] { "✓ No problems found", "✓ Muammo topilmadi", "✓ Проблем не найдено" },
            ["wire.list"] = new[] { "Wires: {0}", "Simlar: {0}", "Провода: {0}" },
            ["wire.none"] = new[] { "No wires yet. Click a pin to start one.", "Hali sim yoʻq. Boshlash uchun pinni bosing.", "Проводов пока нет. Щёлкните вывод, чтобы начать." },
            ["wire.from"] = new[] { "From {0}: now click the other end.", "{0} dan: endi ikkinchi uchini bosing.", "От {0}: теперь щёлкните второй конец." },
            ["wire.lookAt"] = new[] { "Look at", "Qarash", "Показать" },
            ["wire.whole"] = new[] { "Whole robot", "Butun robot", "Весь робот" },
            ["wire.byList"] = new[] { "Connect from the lists", "Roʻyxatdan ulash", "Соединить по спискам" },
            ["wire.addFromList"] = new[] { "Add wire", "Sim qoʻshish", "Добавить провод" },
            ["wire.full"] = new[] { "{0} has no room for another wire: a header pin takes one jumper, a screw terminal two. Remove the old wire first.", "{0} ga yana sim ulab boʻlmaydi: pinga bitta sim, vintli klemmaga ikkita sim sigʻadi. Avval eski simni olib tashlang.", "К {0} больше нельзя подключить провод: на штырёк надевается одна перемычка, в винтовую клемму входят два провода. Сначала уберите старый провод." },
            ["wire.duplicate"] = new[] { "Those pins are already joined by a wire.", "Bu pinlar allaqachon sim bilan ulangan.", "Эти выводы уже соединены проводом." },
            ["wire.length"] = new[] { "{0} → {1} · {2:F0} mm", "{0} → {1} · {2:F0} mm", "{0} → {1} · {2:F0} мм" },
            ["wire.noParts"] = new[] { "Add parts in Build first: wires join the pins of parts.", "Avval Yigʻish boʻlimida qismlar qoʻshing: simlar qismlarning pinlarini ulaydi.", "Сначала добавьте детали в сборке: провода соединяют выводы деталей." },
            ["garage.hint.wireShape"] = new[] { "Drag the wire to bend it · drag a point to move it · Del removes the chosen point (or the wire) · Glue sticks it to a plate or part · Esc lets go", "Simni egish uchun uni torting · nuqtani surish uchun uni torting · Del tanlangan nuqtani (yoki simni) olib tashlaydi · Yopishtirish uni plastina yoki qismga yopishtiradi · Esc tanlovni bekor qiladi", "Потяните провод, чтобы изогнуть его · потяните точку, чтобы передвинуть её · Del убирает выбранную точку (или провод) · «Приклеить» крепит его к пластине или детали · Esc снимает выбор" },
            ["wire.gluingHint"] = new[] { "Gluing: click a plate or a part where the wire should be glued · Esc stops", "Yopishtirish: sim yopishtiriladigan plastina yoki qismni bosing · Esc toʻxtatadi", "Приклеивание: щёлкните пластину или деталь, где приклеить провод · Esc — закончить" },
            ["wire.shape"] = new[] { "Shape this wire", "Simning yoʻli", "Форма провода" },
            ["wire.shapeHint"] = new[] { "Drag the wire to add a bend point it will pass through, and drag a point to move it. Glue sticks the wire to a plate or part with hot glue.", "Simni tortsangiz, u oʻtadigan egilish nuqtasi paydo boʻladi; nuqtani tortib suring. Yopishtirish simni plastina yoki qismga issiq yelim bilan yopishtiradi.", "Потяните провод — появится точка изгиба, через которую он пройдёт; точку можно перетаскивать. «Приклеить» крепит провод к пластине или детали термоклеем." },
            ["wire.glue"] = new[] { "Glue", "Yopishtirish", "Приклеить" },
            ["wire.straighten"] = new[] { "Let it find its way", "Yoʻlni oʻzi topsin", "Проложить заново" },
            ["wire.points"] = new[] { "{0} points, {1} glued", "{0} ta nuqta, {1} tasi yopishtirilgan", "Точек: {0}, приклеено: {1}" },
            ["wire.gluePoint"] = new[] { "Glue this point", "Nuqtani yopishtirish", "Приклеить точку" },
            ["wire.unglue"] = new[] { "Unglue", "Yelimdan ajratish", "Отклеить" },
            ["wire.removePoint"] = new[] { "Remove point", "Nuqtani olib tashlash", "Убрать точку" },
            ["wire.glueHere"] = new[] { "Glue here: {0}", "Shu yerga yopishtirish: {0}", "Приклеить сюда: {0}" },
            ["wire.glueWheel"] = new[] { "A wheel turns: glue the wire to a plate or a part.", "Gʻildirak aylanadi: simni plastina yoki qismga yopishtiring.", "Колесо вращается: приклейте провод к пластине или детали." },
            ["wire.glueNothing"] = new[] { "Nothing to glue to there: click a plate or a part.", "U yerda yopishtiradigan narsa yoʻq: plastina yoki qismni bosing.", "Там не к чему приклеить: щёлкните пластину или деталь." },
            ["wire.glueFar"] = new[] { "Nothing near this point to glue it to: drag it onto a plate or a part first.", "Bu nuqta yonida yopishtiradigan narsa yoʻq: avval uni plastina yoki qism ustiga suring.", "Рядом с точкой не к чему приклеить: сначала перетащите её к пластине или детали." },
            ["chk.noBattery"] = new[] { "No battery: nothing has power.", "Batareya yoʻq: hech narsaga quvvat bormaydi.", "Нет батареи: ничего не получает питания." },
            ["chk.shortCircuit"] = new[] { "Short circuit: battery + and − are joined. The wires get hot and the cells drain fast.", "Qisqa tutashuv: batareyaning + va − uchlari ulangan. Simlar qiziydi va batareya tez tugaydi.", "Короткое замыкание: + и − батареи соединены. Провода греются, батарейки быстро садятся." },
            ["chk.driverUnpowered"] = new[] { "The L298N has no motor supply: wire battery + to +12V and battery − to GND.", "L298N ga motor quvvati kelmayapti: batareya + ni +12V ga, batareya − ni GND ga ulang.", "На L298N нет питания моторов: подключите + батареи к +12V, а − батареи к GND." },
            ["chk.noBoard"] = new[] { "No Arduino board: nothing runs your code.", "Arduino platasi yoʻq: kodingizni bajaradigan narsa yoʻq.", "Нет платы Arduino: код некому выполнять." },
            ["chk.board5vOvervoltage"] = new[] { "Battery + is on the Uno's 5V pin: about 6 V there burns the board (F7). Use VIN or the L298N's +5V.", "Batareya + Uno ning 5V piniga ulangan: u yerdagi taxminan 6 V platani kuydiradi (F7). VIN yoki L298N ning +5V chiqishidan foydalaning.", "+ батареи подключён к выводу 5V платы Uno: около 6 В сожгут плату (F7). Используйте VIN или +5V драйвера L298N." },
            ["chk.boardUnpowered"] = new[] { "The Uno has no power: wire its 5V to the L298N's +5V, or VIN to battery +.", "Uno ga quvvat kelmayapti: uning 5V pinini L298N ning +5V chiqishiga yoki VIN ni batareya + ga ulang.", "Плата Uno без питания: подключите её 5V к +5V драйвера L298N или VIN к + батареи." },
            ["chk.fiveVoltOnVin"] = new[]
            {
                "The L298N's +5V goes to the Uno's VIN, but VIN needs 7-12 V (it feeds the Uno's own 5 V regulator), so the Uno gets too little to run. Move that wire from VIN to the Uno's 5V pin.",
                "L298N ning +5V chiqishi Uno ning VIN piniga ulangan, lekin VIN ga 7-12 V kerak (u Uno ning oʻz 5 V stabilizatorini taʼminlaydi), shuning uchun Uno ishlashga yetarli quvvat olmaydi. Bu simni VIN dan Uno ning 5V piniga oʻtkazing.",
                "+5V драйвера L298N подключён к VIN платы Uno, но на VIN нужно 7–12 В (он питает собственный стабилизатор 5 В платы), поэтому Uno не хватает питания. Перенесите этот провод с VIN на вывод 5V платы Uno.",
            },
            ["chk.noGround"] = new[] { "No common ground: join a GND pin of the Uno to the battery's − (through the L298N's GND).", "Umumiy yer yoʻq: Uno ning GND pinini batareyaning − uchiga (L298N ning GND orqali) ulang.", "Нет общей земли: соедините GND платы Uno с − батареи (через GND драйвера L298N)." },
            ["chk.driver5vLow"] = new[] { "• The L298N's 5 V regulator needs about 7 V; from 4×AA it gives a little under 5 V. That works, as on the real kit.", "• L298N ning 5 V stabilizatoriga taxminan 7 V kerak; 4×AA dan u 5 V dan biroz kam beradi. Haqiqiy toʻplamdagidek ishlaydi.", "• Стабилизатору 5 В на L298N нужно около 7 В; от 4×AA он даёт чуть меньше 5 В. Это работает, как в настоящем наборе." },
            ["chk.pinsJoined"] = new[] { "Uno pins {0} and {1} are joined by wires: when one is HIGH and the other LOW, they fight.", "Uno ning {0} va {1} pinlari simlar bilan ulangan: biri HIGH, ikkinchisi LOW boʻlsa, ular bir-biriga qarshi ishlaydi.", "Выводы {0} и {1} платы Uno соединены: когда один HIGH, а другой LOW, они мешают друг другу." },
            ["chk.sonarOvervoltage"] = new[] { "Battery + is on the HC-SR04's VCC: more than 5.5 V burns the sensor (F26).", "Batareya + HC-SR04 ning VCC piniga ulangan: 5,5 V dan ortigʻi sensorni kuydiradi (F26).", "+ батареи подключён к VCC датчика HC-SR04: больше 5,5 В сожгут датчик (F26)." },
            ["chk.sonarUnpowered"] = new[] { "The HC-SR04 has no power: VCC needs 5 V and GND a ground.", "HC-SR04 ga quvvat kelmayapti: VCC ga 5 V, GND ga yer kerak.", "Датчик HC-SR04 без питания: на VCC нужно 5 В, а GND — на землю." },
            ["chk.ledNoGround"] = new[] { "{0}: its − pin is not on ground (GND).", "{0}: uning − pini yerga (GND) ulanmagan.", "{0}: вывод − не подключён к земле (GND)." },
            ["chk.ledPin"] = new[] { "{0}: its S pin is not wired to an Uno pin.", "{0}: S pini Uno pinlaridan biriga ulanmagan.", "{0}: вывод S не подключён к выводу Uno." },
            ["chk.servoUnpowered"] = new[] { "{0} has no power: V+ wants 5–6 V (the Uno's 5V, the L298N's +5V or the battery) and GND on ground.", "{0} taʼminotsiz: V+ ga 5–6 V (Uno 5V, L298N +5V yoki batareya) kerak, GND esa yerga ulanadi.", "{0} без питания: на V+ нужно 5–6 В (5V Uno, +5V L298N или батарея), а GND — на землю." },
            ["chk.servoPin"] = new[] { "{0}: its signal lead (orange) is not wired to an Uno pin.", "{0}: signal simi (toʻq sariq) Uno pinlaridan biriga ulanmagan.", "{0}: сигнальный провод (оранжевый) не подключён к выводу Uno." },
            ["chk.sonarPin"] = new[] { "The HC-SR04's {0} pin is not wired to an Uno pin.", "HC-SR04 ning {0} pini Uno pinlaridan biriga ulanmagan.", "Вывод {0} датчика HC-SR04 не подключён к выводу Uno." },
            ["chk.inputFloating"] = new[] { "L298N {0} is not wired to the Uno: that input floats.", "L298N ning {0} kirishi Uno ga ulanmagan: bu kirish osilib qolgan.", "Вход {0} драйвера L298N не подключён к Uno: вход «висит»." },
            ["chk.motorOnGpio"] = new[] { "{0} motor is wired to Uno pin {1}: a pin gives 40 mA at most, a TT motor needs up to 1 A. Motors go on the L298N's OUT terminals.", "{0} motor Uno ning {1} piniga ulangan: pin koʻpi bilan 40 mA beradi, TT motorga esa 1 A gacha kerak. Motorlar L298N ning OUT chiqishlariga ulanadi.", "{0} мотор подключён к выводу {1} платы Uno: вывод даёт не больше 40 мА, а мотору TT нужно до 1 А. Моторы подключают к выходам OUT драйвера L298N." },
            ["chk.motorNotConnected"] = new[] { "{0} motor is not connected: put M+ and M− on OUT1 and OUT2, or on OUT3 and OUT4.", "{0} motor ulanmagan: M+ va M− ni OUT1 va OUT2 ga yoki OUT3 va OUT4 ga ulang.", "{0} мотор не подключён: подключите M+ и M− к OUT1 и OUT2 или к OUT3 и OUT4." },
            ["body.shape"] = new[] { "Shape", "Shakl", "Форма" },
            ["body.rect"] = new[] { "Rectangle", "Toʻrtburchak", "Прямоугольник" },
            ["body.rounded"] = new[] { "Rounded", "Burchaklari yumaloq", "Скруглённый" },
            ["body.round"] = new[] { "Round", "Doira", "Круглый" },
            ["body.length"] = new[] { "Length, mm", "Uzunlik, mm", "Длина, мм" },
            ["body.width"] = new[] { "Width, mm", "Kenglik, mm", "Ширина, мм" },
            ["body.diameter"] = new[] { "Diameter, mm", "Diametr, mm", "Диаметр, мм" },
            ["body.thickness"] = new[] { "Thickness, mm", "Qalinlik, mm", "Толщина, мм" },
            ["body.corner"] = new[] { "Corner radius, mm", "Burchak radiusi, mm", "Радиус углов, мм" },
            ["body.walls"] = new[] { "Side walls, mm", "Yon devorlar, mm", "Бортики, мм" },
            ["body.decks"] = new[] { "Decks", "Qavatlar", "Ярусы" },
            ["body.holes"] = new[] { "M3 hole grid", "M3 teshiklar toʻri", "Сетка отверстий M3" },
            ["body.pitch"] = new[] { "Hole spacing, mm", "Teshiklar oraligʻi, mm", "Шаг отверстий, мм" },
            ["body.material"] = new[] { "Material", "Material", "Материал" },
            ["body.acrylic"] = new[] { "Acrylic", "Akril", "Акрил" },
            ["body.pla"] = new[] { "PLA (3D print)", "PLA (3D bosma)", "PLA (3D-печать)" },
            ["body.plywood"] = new[] { "Plywood", "Fanera", "Фанера" },
            ["body.size"] = new[] { "Size: {0:F0} × {1:F0} × {2:F1} mm", "Oʻlcham: {0:F0} × {1:F0} × {2:F1} mm", "Размер: {0:F0} × {1:F0} × {2:F1} мм" },
            ["body.plates"] = new[] { "Plates: {0}, with {1} holes each", "Panellar: {0} ta, har birida {1} ta teshik", "Пластин: {0}, в каждой отверстий: {1}" },
            ["body.mass"] = new[] { "Plates: {0:F0} g ({1:F1} cm³ of {2})", "Panellar: {0:F0} g ({2}, {1:F1} sm³)", "Пластины: {0:F0} г ({1:F1} см³, {2})" },
            ["body.kernel"] = new[] { "Rebuilt by Manifold in {0:F1} ms", "Manifold {0:F1} ms da qayta qurdi", "Manifold перестроил за {0:F1} мс" },
            ["body.export"] = new[] { "Export STL", "STL eksport", "Экспорт STL" },
            ["body.exported"] = new[] { "Saved {0}", "Saqlandi: {0}", "Сохранено: {0}" },
            ["body.openFolder"] = new[] { "Open folder", "Jildni ochish", "Открыть папку" },
            ["body.stlNote"] = new[] { "The STL holds every plate side by side, in millimetres, ready for a slicer or a laser cutter.", "STL faylida barcha panellar yonma-yon, millimetrlarda: slayser yoki lazer kesgich uchun tayyor.", "В STL все пластины лежат рядом, в миллиметрах: файл готов для слайсера или лазерной резки." },
            ["warn.wiring"] = new[] { "⚠ Wiring: {0} problem(s), see Wire", "⚠ Simlar: {0} ta muammo, Simlash boʻlimiga qarang", "⚠ Провода: проблем — {0}, см. «Провода»" },
            ["warn.boardBurnt"] = new[] { "⚠ Arduino Uno burnt out", "⚠ Arduino Uno kuyib qolgan", "⚠ Arduino Uno сгорела" },
            ["warn.sonarBurnt"] = new[] { "⚠ HC-SR04 burnt out", "⚠ HC-SR04 kuyib qolgan", "⚠ HC-SR04 сгорел" },
            ["card.factoryBlink"] = new[] { "not uploaded yet: the board runs Blink", "hali yuklanmagan: plata Blink ni bajaradi", "ещё не загружен: плата выполняет Blink" },
            ["rep.wiringOk"] = new[] { "Wiring checked: no problems", "Simlar tekshirildi: muammo yoʻq", "Провода проверены: проблем нет" },
            ["rep.wiringBad"] = new[] { "Wiring: {0} problem(s), see Wire", "Simlar: {0} ta muammo, Simlash boʻlimiga qarang", "Провода: проблем — {0}, см. «Провода»" },
            ["rep.factoryBlink"] = new[] { "No sketch uploaded yet: the board runs its factory Blink", "Hali sketch yuklanmagan: plata zavod Blink dasturini bajaradi", "Скетч ещё не загружен: плата выполняет заводской Blink" },
            ["rep.noBattery"] = new[] { "No battery holder on this robot", "Bu robotda batareya qutisi yoʻq", "На этом роботе нет батарейного отсека" },
            ["rep.whyF7"] = new[] { "About 6 V from the battery reached the Uno's 5V pin. That pin skips the regulator, and the ATmega328P takes 6 V at most (5.5 V to be safe), so the board burnt out. Feed the Uno through VIN (7–12 V) or from a 5 V regulator such as the L298N's +5V.", "Batareyadan taxminan 6 V Uno ning 5V piniga yetib keldi. Bu pin stabilizatorni chetlab oʻtadi, ATmega328P esa koʻpi bilan 6 V ga (xavfsiz chegara 5,5 V) chidaydi, shuning uchun plata kuydi. Uno ni VIN (7–12 V) orqali yoki L298N ning +5V kabi 5 V stabilizatoridan taʼminlang.", "Около 6 В от батареи попали на вывод 5V платы Uno. Этот вывод идёт в обход стабилизатора, а ATmega328P выдерживает не больше 6 В (безопасно — 5,5 В), поэтому плата сгорела. Питайте Uno через VIN (7–12 В) или от стабилизатора 5 В, например +5V драйвера L298N." },
            ["rep.whyF26"] = new[] { "The HC-SR04 got about 6 V on VCC. It is a 5 V part (5.5 V at most), so it burnt out. Feed it from the Uno's 5V or the L298N's +5V.", "HC-SR04 ning VCC piniga taxminan 6 V berildi. Bu 5 V li qism (koʻpi bilan 5,5 V), shuning uchun u kuydi. Uni Uno ning 5V yoki L298N ning +5V chiqishidan taʼminlang.", "На VCC датчика HC-SR04 пришло около 6 В. Это деталь на 5 В (максимум 5,5 В), поэтому он сгорел. Питайте его от 5V платы Uno или +5V драйвера L298N." },
            ["board.none"] = new[] { "no board", "plata yoʻq", "нет платы" },
            ["board.running"] = new[] { "running", "ishlamoqda", "работает" },
            ["board.unpowered"] = new[] { "no power: check the wiring", "quvvat yoʻq: simlarni tekshiring", "нет питания: проверьте провода" },
            ["board.burnt"] = new[] { "burnt out", "kuyib qolgan", "сгорела" },
            ["board.batteryEmpty"] = new[] { "battery empty", "batareya tugagan", "батарея разряжена" },
            ["studio.title"] = new[] { "Body Studio", "Korpus studiyasi", "Студия корпуса" },
            ["studio.back"] = new[] { "Garage", "Garaj", "Гараж" },
            ["studio.undo"] = new[] { "Undo (Ctrl+Z)", "Bekor qilish (Ctrl+Z)", "Отменить (Ctrl+Z)" },
            ["studio.redo"] = new[] { "Redo (Ctrl+Y)", "Qaytarish (Ctrl+Y)", "Повторить (Ctrl+Y)" },
            ["studio.moveTip"] = new[] { "Move (W)", "Siljitish (W)", "Сдвиг (W)" },
            ["studio.rotateTip"] = new[] { "Turn (E)", "Burish (E)", "Поворот (E)" },
            ["studio.sizeTip"] = new[] { "Size (R)", "Oʻlcham (R)", "Размер (R)" },
            ["studio.snap"] = new[] { "Snap", "Qadam", "Шаг" },
            ["studio.draw"] = new[] { "Draw", "Chizish", "Рисовать" },
            ["studio.import"] = new[] { "Import", "Import", "Импорт" },
            ["studio.export"] = new[] { "STL", "STL", "STL" },
            ["studio.parts"] = new[] { "Parts", "Qismlar", "Детали" },
            ["studio.exportTip"] = new[] { "Export the body as STL", "Korpusni STL qilib saqlash", "Сохранить корпус в STL" },
            ["studio.partsTip"] = new[] { "Show or hide the electronics", "Elektronikani koʻrsatish yoki yashirish", "Показать или скрыть электронику" },
            ["studio.shapes"] = new[] { "Shapes", "Shakllar", "Фигуры" },
            ["studio.solid"] = new[] { "Solid", "Qattiq", "Тело" },
            ["studio.hole"] = new[] { "Hole", "Teshik", "Отверстие" },
            ["studio.addAs"] = new[] { "New shapes are added as:", "Yangi shakllar quyidagicha qoʻshiladi:", "Новые фигуры добавляются как:" },
            ["studio.more"] = new[] { "Your own shapes", "Oʻz shakllaringiz", "Свои фигуры" },
            ["shape.box"] = new[] { "Box", "Quti", "Куб" },
            ["shape.rounded"] = new[] { "Rounded box", "Yumaloq quti", "Скруглённый куб" },
            ["shape.cylinder"] = new[] { "Cylinder", "Silindr", "Цилиндр" },
            ["shape.cone"] = new[] { "Cone", "Konus", "Конус" },
            ["shape.sphere"] = new[] { "Sphere", "Shar", "Шар" },
            ["shape.wedge"] = new[] { "Wedge", "Pona", "Клин" },
            ["shape.tube"] = new[] { "Tube", "Quvur", "Труба" },
            ["shape.extrusion"] = new[] { "Drawn shape", "Chizilgan shakl", "Нарисованная фигура" },
            ["shape.imported"] = new[] { "Imported model", "Import qilingan model", "Импортированная модель" },
            ["shape.draw"] = new[] { "Draw outline", "Kontur chizish", "Нарисовать контур" },
            ["shape.import"] = new[] { "Upload STL / OBJ", "STL / OBJ yuklash", "Загрузить STL / OBJ" },
            ["studio.base"] = new[] { "Base plates", "Asosiy panellar", "Основные пластины" },
            ["studio.shapeList"] = new[] { "Shapes on the body ({0})", "Korpusdagi shakllar ({0})", "Фигуры на корпусе ({0})" },
            ["studio.noShapes"] = new[] { "No body yet: take a plate or another shape from the library, draw an outline, or upload an STL or OBJ file.", "Hali korpus yoʻq: kutubxonadan plastina yoki boshqa shaklni oling, kontur chizing yoki STL yoki OBJ faylini yuklang.", "Корпуса пока нет: возьмите из библиотеки пластину или другую фигуру, нарисуйте контур или загрузите файл STL или OBJ." },
            ["studio.holeTag"] = new[] { "hole", "teshik", "отверстие" },
            ["studio.position"] = new[] { "Position, mm", "Joylashuv, mm", "Положение, мм" },
            ["studio.rotation"] = new[] { "Rotation, °", "Burilish, °", "Поворот, °" },
            ["studio.sizeMm"] = new[] { "Size, mm (x width · y height · z length)", "Oʻlcham, mm (x eni · y balandligi · z boʻyi)", "Размер, мм (x ширина · y высота · z длина)" },
            ["studio.keep"] = new[] { "Keep proportions", "Nisbatni saqlash", "Сохранять пропорции" },
            ["studio.corner"] = new[] { "Corner radius, mm", "Burchak radiusi, mm", "Радиус скругления, мм" },
            ["studio.wall"] = new[] { "Wall, mm", "Devor qalinligi, mm", "Толщина стенки, мм" },
            ["studio.top"] = new[] { "Top, % of the base", "Uchi, asosning %", "Верх, % от основания" },
            ["studio.height"] = new[] { "Height, mm", "Balandlik, mm", "Высота, мм" },
            ["studio.duplicate"] = new[] { "Duplicate", "Nusxa", "Копия" },
            ["studio.mirror"] = new[] { "Mirror copy", "Oynali nusxa", "Зеркальная копия" },
            ["studio.drop"] = new[] { "Put on deck", "Panelga qoʻyish", "На пластину" },
            ["studio.delete"] = new[] { "Delete", "Oʻchirish", "Удалить" },
            ["studio.file"] = new[] { "File: {0}, {1} triangles", "Fayl: {0}, {1} ta uchburchak", "Файл: {0}, треугольников: {1}" },
            ["studio.open"] = new[] { "This model is not a closed solid, so it cannot cut holes or join other shapes. It is shown as it is; close its gaps in a 3D program and upload it again.", "Bu model yopiq jism emas, shuning uchun u teshik ochmaydi va boshqa shakllar bilan birlashmaydi. U boricha koʻrsatiladi; 3D dasturda tirqishlarini yoping va qayta yuklang.", "Эта модель не замкнута, поэтому она не вырезает отверстия и не объединяется с другими фигурами. Она показана как есть; закройте щели в 3D-программе и загрузите её снова." },
            ["studio.shapeVolume"] = new[] { "Volume ≈ {0:F1} cm³, ≈ {1:F0} g", "Hajmi ≈ {0:F1} sm³, ≈ {1:F0} g", "Объём ≈ {0:F1} см³, ≈ {1:F0} г" },
            ["studio.bodyMass"] = new[] { "Body: {0:F0} g, {1:F1} cm³ of {2}", "Korpus: {0:F0} g, {2}, {1:F1} sm³", "Корпус: {0:F0} г, {1:F1} см³, {2}" },
            ["studio.hint.none"] = new[] { "Click a shape or part in the library, then click where it goes · click something on the robot to select it · Shift+click selects more · right-drag turns the view", "Kutubxonadagi shakl yoki qismni bosing, soʻng uni qoʻyiladigan joyni bosing · tanlash uchun robotdagi narsani bosing · Shift+bosish koʻproq tanlaydi · oʻng tugma bilan tortib koʻrinishni buring", "Щёлкните фигуру или деталь в библиотеке, затем место, куда её поставить · щёлкните по роботу, чтобы выбрать · Shift+щелчок добавляет к выбору · правая кнопка поворачивает вид" },
            ["studio.hint.draw"] = new[] { "Click points on the deck · click the first point or press Enter to finish · Backspace removes the last point · Esc cancels", "Panelda nuqtalarni bosing · tugatish uchun birinchi nuqtani bosing yoki Enter ni bosing · Backspace oxirgi nuqtani oʻchiradi · Esc bekor qiladi", "Ставьте точки на пластине · чтобы закончить, нажмите первую точку или Enter · Backspace удаляет последнюю точку · Esc отменяет" },
            ["studio.selected"] = new[] { "{0} {1} · {2:0.#} × {3:0.#} × {4:0.#} mm at x {5:0.#}, y {6:0.#}, z {7:0.#}", "{0} {1} · {2:0.#} × {3:0.#} × {4:0.#} mm, x {5:0.#}, y {6:0.#}, z {7:0.#} da", "{0} {1} · {2:0.#} × {3:0.#} × {4:0.#} мм, x {5:0.#}, y {6:0.#}, z {7:0.#}" },
            ["studio.importFailed"] = new[] { "Could not read {0}: {1}", "{0} oʻqilmadi: {1}", "Не удалось прочитать {0}: {1}" },
            ["studio.tooMany"] = new[] { "{0} has {1} triangles; the limit is 200 000. Simplify it in a 3D program first.", "{0} da {1} ta uchburchak bor; chegara 200 000. Avval uni 3D dasturda soddalashtiring.", "В {0} {1} треугольников, а предел 200 000. Сначала упростите модель в 3D-программе." },
            ["studio.metres"] = new[] { "The file looked like it was in metres, so it was scaled ×1000.", "Fayl metrlarda boʻlganga oʻxshaydi, shuning uchun ×1000 kattalashtirildi.", "Похоже, файл в метрах, поэтому он увеличен ×1000." },
            ["studio.imported"] = new[] { "Imported {0}: {1:0.#} × {2:0.#} × {3:0.#} mm", "{0} import qilindi: {1:0.#} × {2:0.#} × {3:0.#} mm", "Импортирован {0}: {1:0.#} × {2:0.#} × {3:0.#} мм" },
            ["studio.big"] = new[] { "The model is {0:0} mm long; check that its units were millimetres.", "Model uzunligi {0:0} mm; uning birligi millimetr ekanini tekshiring.", "Длина модели {0:0} мм; проверьте, что она была в миллиметрах." },
            ["studio.selfCross"] = new[] { "The outline crosses itself; draw it without crossing lines.", "Kontur oʻzini kesib oʻtadi; uni chiziqlar kesishmaydigan qilib chizing.", "Контур пересекает сам себя; нарисуйте его без пересечений." },
            ["studio.tooFew"] = new[] { "An outline needs at least three points.", "Kontur uchun kamida uchta nuqta kerak.", "Для контура нужно не меньше трёх точек." },
            ["studio.noDialog"] = new[] { "Opening files works in the Windows version only.", "Fayl ochish faqat Windows versiyasida ishlaydi.", "Открытие файлов работает только в версии для Windows." },
            ["studio.fileTitle"] = new[] { "Upload a 3D model (STL or OBJ, millimetres)", "3D model yuklash (STL yoki OBJ, millimetr)", "Загрузить 3D-модель (STL или OBJ, миллиметры)" },
            ["studio.fileFilter"] = new[] { "3D models (*.stl, *.obj)", "3D modellar (*.stl, *.obj)", "3D-модели (*.stl, *.obj)" },
            ["studio.stats"] = new[] { "{0:F1} cm³ · {1:F0} g · Manifold {2:F0} ms", "{0:F1} sm³ · {1:F0} g · Manifold {2:F0} ms", "{0:F1} см³ · {1:F0} г · Manifold {2:F0} мс" },
            ["studio.tabShapes"] = new[] { "Shapes", "Shakllar", "Фигуры" },
            ["studio.tabParts"] = new[] { "Parts", "Qismlar", "Детали" },
            ["studio.partsNote"] = new[] { "Real parts keep their size. Click one, then click where it goes: boards stand on a plate, motors and the caster hang under it.", "Haqiqiy qismlar oʻz oʻlchamida qoladi. Birini bosing, soʻng joyini bosing: platalar plastina ustiga turadi, motorlar va rolik uning ostiga osiladi.", "Настоящие детали не меняют размер. Щёлкните деталь, затем место: платы встают на пластину, моторы и опора подвешиваются под ней." },
            ["studio.partCount"] = new[] { "{0}/{1} · {2:0.#} g", "{0}/{1} · {2:0.#} g", "{0}/{1} · {2:0.#} г" },
            ["studio.material"] = new[] { "Material", "Material", "Материал" },
            ["studio.density"] = new[] { "Density {0:0.##} g/cm³", "Zichligi {0:0.##} g/sm³", "Плотность {0:0.##} г/см³" },
            ["studio.clear"] = new[] { "Clear", "Shaffof", "Прозрачный" },
            ["studio.hint.carry"] = new[] { "Move the mouse to where it goes and click to set it down · Esc puts it back", "Sichqonchani kerakli joyga olib boring va qoʻyish uchun bosing · Esc qaytaradi", "Наведите мышь туда, где должна быть деталь, и щёлкните · Esc — вернуть" },
            ["studio.hint.part"] = new[] { "Drag it onto a plate · the cone lifts it · the curved arrows turn it (Shift: 45°, Ctrl: 1°) · D drops it onto the workplane", "Uni plastinaga torting · konus koʻtaradi · egri strelkalar buradi (Shift: 45°, Ctrl: 1°) · D ishchi tekislikka tushiradi", "Перетащите на пластину · конус поднимает · изогнутые стрелки поворачивают (Shift: 45°, Ctrl: 1°) · D опускает на рабочую плоскость" },
            ["studio.fixedSize"] = new[] { "a real part: its size cannot change", "haqiqiy qism: oʻlchami oʻzgarmaydi", "настоящая деталь: её размер не меняется" },
            ["studio.selectedMany"] = new[] { "{0} selected", "{0} ta tanlandi", "Выбрано: {0}" },
            ["studio.hint.group"] = new[] { "Ctrl+G groups them: holes then cut the solids of the group", "Ctrl+G guruhlaydi: shunda teshiklar guruhdagi jismlarni kesadi", "Ctrl+G группирует: тогда отверстия вырезают тела группы" },
            ["studio.below"] = new[] { "Something is {0:0} mm below the workplane", "Nimadir ishchi tekislikdan {0:0} mm pastda", "Что-то на {0:0} мм ниже рабочей плоскости" },
            ["studio.above"] = new[] { "The robot's lowest point is {0:0} mm above the workplane", "Robotning eng past nuqtasi ishchi tekislikdan {0:0} mm balandda", "Нижняя точка робота на {0:0} мм выше рабочей плоскости" },
            ["studio.ground"] = new[] { "Stand it on the workplane", "Ishchi tekislikka qoʻyish", "Поставить на рабочую плоскость" },
            ["studio.groupNeedsTwo"] = new[] { "Select two or more shapes with Shift+click to group them.", "Guruhlash uchun Shift+bosish bilan ikki yoki undan koʻp shaklni tanlang.", "Чтобы сгруппировать, выберите две фигуры или больше (Shift+щелчок)." },
            ["studio.partList"] = new[] { "Parts ({0})", "Qismlar ({0})", "Детали ({0})" },
            ["studio.noParts"] = new[] { "No parts yet: open the Parts tab of the library.", "Hali qism yoʻq: kutubxonaning Qismlar yorligʻini oching.", "Деталей пока нет: откройте вкладку «Детали» в библиотеке." },
            ["studio.bodyTotal"] = new[] { "Body: {0:F0} g, {1:F1} cm³", "Korpus: {0:F0} g, {1:F1} sm³", "Корпус: {0:F0} г, {1:F1} см³" },
            ["studio.group"] = new[] { "Group (Ctrl+G)", "Guruhlash (Ctrl+G)", "Сгруппировать (Ctrl+G)" },
            ["studio.ungroup"] = new[] { "Ungroup", "Guruhni ajratish", "Разгруппировать" },
            ["studio.groupNote"] = new[] { "In a group, holes cut the solids; each solid keeps its own material.", "Guruhda teshiklar jismlarni kesadi; har bir jism oʻz materialini saqlaydi.", "В группе отверстия вырезают тела; каждое тело сохраняет свой материал." },
            ["studio.groupHas"] = new[] { "{0} shapes in this group", "Bu guruhda {0} ta shakl", "Фигур в группе: {0}" },
            ["studio.holeAlone"] = new[] { "A hole on its own cuts nothing: select it with the shape it should cut (Shift+click) and group them (Ctrl+G).", "Yolgʻiz teshik hech narsani kesmaydi: uni kesishi kerak boʻlgan shakl bilan birga tanlang (Shift+bosish) va guruhlang (Ctrl+G).", "Отверстие само по себе ничего не вырезает: выберите его вместе с фигурой (Shift+щелчок) и сгруппируйте (Ctrl+G)." },
            ["studio.wheelEnd"] = new[] { "Wheel to the other end", "Gʻildirakni boshqa uchiga", "Колесо на другой конец" },
            ["studio.wheelEndNote"] = new[] { "The motor's white shaft comes out on both sides: put the wheel on the end that faces out. Two motors facing the same way, each with its wheel outside, make a symmetric robot, and + on M+ drives both forward.", "Motorning oq vali ikki tomondan chiqadi: gʻildirakni tashqariga qaragan uchiga qoʻying. Bir xil qaragan ikki motor, gʻildiraklari tashqarida boʻlsa, robot simmetrik boʻladi va M+ ga + berilsa ikkalasi ham oldinga yuradi.", "Белый вал мотора выходит с обеих сторон: наденьте колесо на конец, который смотрит наружу. Два мотора, повёрнутые одинаково, с колёсами снаружи — робот симметричный, и «+» на M+ везёт вперёд оба." },
            ["studio.noDrive"] = new[] { "The shaft points up or down: this wheel cannot drive.", "Val yuqoriga yoki pastga qaragan: bu gʻildirak yurgiza olmaydi.", "Вал направлен вверх или вниз: это колесо не может ехать." },
            ["studio.driveForward"] = new[] { "{0} motor: + on M+ drives the robot forward.", "{0} motor: M+ ga + berilsa robot oldinga yuradi.", "{0} мотор: «+» на M+ везёт робота вперёд." },
            ["studio.driveBack"] = new[] { "{0} motor: + on M+ drives the robot backward, so its leads go to the driver swapped.", "{0} motor: M+ ga + berilsa robot orqaga yuradi, shuning uchun uning simlari drayverga almashtirib ulanadi.", "{0} мотор: «+» на M+ везёт робота назад, поэтому его выводы подключают к драйверу наоборот." },
            ["studio.partPlaceNote"] = new[] { "Drag a part onto a plate: boards stand on it, motors and the caster hang under it. E turns it; D drops it onto the workplane.", "Qismni plastinaga torting: platalar uning ustiga turadi, motorlar va rolik ostiga osiladi. E buradi; D ishchi tekislikka tushiradi.", "Перетащите деталь на пластину: платы встают на неё, моторы и опора подвешиваются под ней. E поворачивает; D опускает на рабочую плоскость." },
            ["studio.pitch"] = new[] { "Hole spacing, mm (0: none)", "Teshiklar oraligʻi, mm (0: yoʻq)", "Шаг отверстий, мм (0 — нет)" },
            ["studio.holeSize"] = new[] { "Hole diameter, mm", "Teshik diametri, mm", "Диаметр отверстий, мм" },
            ["shape.plate"] = new[] { "Plate with holes", "Teshikli plastina", "Пластина с отверстиями" },
            ["shape.group"] = new[] { "Group", "Guruh", "Группа" },
            ["material.pla"] = new[] { "PLA plastic", "PLA plastik", "Пластик PLA" },
            ["material.acrylic"] = new[] { "Acrylic", "Akril", "Акрил" },
            ["material.plywood"] = new[] { "Plywood", "Fanera", "Фанера" },
            ["material.cardboard"] = new[] { "Cardboard", "Karton", "Картон" },
            ["material.evaFoam"] = new[] { "EVA foam", "EVA koʻpik (fomiks)", "Фоамиран (EVA)" },
            ["material.foamBoard"] = new[] { "PVC foam board", "PVX koʻpik taxta", "Вспененный ПВХ" },
            ["material.aluminium"] = new[] { "Aluminium", "Alyuminiy", "Алюминий" },
            ["studio.hint.shape"] = new[] { "Drag to move · white squares size it (Shift keeps proportions, Alt from the middle) · the cone lifts it · the curved arrows turn it · Ctrl: fine steps", "Siljitish uchun torting · oq kvadratlar oʻlchamini oʻzgartiradi (Shift nisbatni saqlaydi, Alt oʻrtadan) · konus koʻtaradi · egri strelkalar buradi · Ctrl: mayda qadam", "Тяните, чтобы сдвинуть · белые квадраты меняют размер (Shift сохраняет пропорции, Alt — от центра) · конус поднимает · изогнутые стрелки поворачивают · Ctrl: мелкий шаг" },
            ["studio.hint.oneGroup"] = new[] { "Drag to move · the cone lifts it · the curved arrows turn it · Ctrl+Shift+G ungroups it", "Siljitish uchun torting · konus koʻtaradi · egri strelkalar buradi · Ctrl+Shift+G guruhni ajratadi", "Тяните, чтобы сдвинуть · конус поднимает · изогнутые стрелки поворачивают · Ctrl+Shift+G разгруппирует" },
            ["edit.nothingToRedo"] = new[] { "Nothing to redo.", "Qaytariladigan narsa yoʻq.", "Повторять нечего." },
            ["view.top"] = new[] { "TOP", "USTI", "ВЕРХ" },
            ["view.bottom"] = new[] { "BOTTOM", "OSTI", "НИЗ" },
            ["view.front"] = new[] { "FRONT", "OLDI", "ПЕРЕД" },
            ["view.back"] = new[] { "BACK", "ORQA", "ЗАД" },
            ["view.left"] = new[] { "LEFT", "CHAP", "ЛЕВО" },
            ["view.right"] = new[] { "RIGHT", "OʻNG", "ПРАВО" },
            ["view.home"] = new[] { "Home view", "Boshlangʻich koʻrinish", "Исходный вид" },
            ["view.fit"] = new[] { "Fit the robot in view", "Robotni toʻliq koʻrsatish", "Показать робота целиком" },
            ["view.hint"] = new[]
            {
                "Click a face, edge or corner to look from there · drag the cube to turn",
                "Oʻsha tomondan qarash uchun yuz, qirra yoki burchakni bosing · aylantirish uchun kubni torting",
                "Щёлкните грань, ребро или угол, чтобы смотреть оттуда · тяните куб, чтобы вращать",
            },
            ["editor.cut"] = new[] { "Cut", "Kesib olish", "Вырезать" },
            ["editor.copy"] = new[] { "Copy", "Nusxalash", "Копировать" },
            ["editor.paste"] = new[] { "Paste", "Qoʻyish", "Вставить" },
            ["editor.selectAll"] = new[] { "Select all", "Hammasini belgilash", "Выделить всё" },
            ["editor.undo"] = new[] { "Undo", "Bekor qilish", "Отменить" },
            ["editor.redo"] = new[] { "Redo", "Qaytarish", "Повторить" },
        };

        public static int Language { get; private set; }
        public static event Action? LanguageChanged;

        public static void SetLanguage(int index)
        {
            Language = Math.Max(0, Math.Min(index, LanguageCodes.Length - 1));
            LanguageChanged?.Invoke();
        }

        public static string Get(string key) =>
            Table.TryGetValue(key, out var texts) ? texts[Language] : key;

        public static string Format(string key, params object[] args) => string.Format(Get(key), args);

        /// <summary>Every string of one language, for the font coverage check.</summary>
        public static string AllText(int language)
        {
            var sb = new StringBuilder();
            foreach (var texts in Table.Values) sb.Append(texts[language]);
            return sb.ToString();
        }
    }
}
